# Use the .NET SDK image to build the application
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

# Copy the solution file and project files
COPY *.sln .
COPY CepApi.Domain/*.csproj ./CepApi.Domain/
COPY CepApi.Domain.Infra/*.csproj ./CepApi.Domain.Infra/
COPY CepApi.Domain.Shared/*.csproj ./CepApi.Domain.Shared/
COPY CepApi.Domain.Api/*.csproj ./CepApi.Domain.Api/

# Restore dependencies
RUN dotnet restore

# Copy the entire project content and build the application
COPY . .
WORKDIR /app
RUN dotnet publish -c Release -o out

# Use the .NET ASP.NET runtime image for the final image
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app

# Copy the published application from the build stage
COPY --from=build /app/out ./

# Set the command to run the application
CMD ["dotnet", "CepApi.Domain.Api.dll"]
