version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: cep_api
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  dotnet-app:
    build:
      context: .
      dockerfile: ./DockerFile
    ports:
      - "80:80"
    depends_on:
      - mysql
      - redis

volumes:
  mysql_data:
