version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_cepapi
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: cep_api
    ports:
      - "6603:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis_cepapi
    ports:
      - "6379:6379"

volumes:
  mysql_data:
